### Coding

> **Question**

### Pandas 与 Numpy 的联系和区别

> **Pandas** 是基于 **Numpy数组**构建的，尤其是**基于数组的函数**和**不使用for循环**的数据处理
> **Pandas** 是专门为处理**表格**和**混杂数据**设计的，而**Numpy**更适合处理**统一的数值数组数据**

In [3]:
import pandas as pd
from pandas import Series, DataFrame

### 1.1 Pandas的数据结构

> **Series** && **DataFrame**

### **Series**：类似于一维数组的对象，由一组**数据(Numpy数据类型)**以及一组与之相关的**数据标签**(索引)组成

> **Series**的字符串表现形式：**索引在左边，值在右边**

> 通过**Series**的**values**和**index**属性获取其**数组**表示形式和**索引对象**

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values # 获取其数组表示形式

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index  # 获取其索引对象 索引从0开始到N-1  左闭右开 range(N)

RangeIndex(start=0, stop=4, step=1)

- **Series**带有一个可以对各个数据点进行**标记的索引**

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
obj2.index

d    4
b    7
a   -5
c    3
dtype: int64


Index(['d', 'b', 'a', 'c'], dtype='object')

- 与**NumPy数组**相比，你可以通过**索引**的方式选取**Series**中的**单个**或**一组值**

In [9]:
obj2['a']  # 通过索引的方式选取Series中的单个或一组值

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2['d']

6

In [12]:
obj2[['c', 'a', 'd']]  # [尽管'c', 'a', 'd']是索引列表，但它包含的是字符串而不是整数

c    3
a   -5
d    6
dtype: int64

- 使用NumPy函数或类似NumPy的运算都会保留索引值的链接
    - 包括根据布尔型数组进行过滤、标量乘法、应用数学函数

In [13]:
obj2[obj2 > 0] 

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2  # 可以将Series看成是一个定长的有序字典，因为它是索引值到数据值的一个映射

True

In [19]:
'e' in obj2

False

- 如果数据被存放在一个Python字典中，也可以直接通过这个字典来创建Series

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [21]:
# Series会根据运算的索引标签自动对齐数据
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [22]:
# 如果只传入一个字典，则结果Series中的索引就是原字典的键 且是 有序排序
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

- **NAN** 即 **Not A Number**: 用于表示缺失或NA值
- **pandas** 的 **isnull** 和 **notnull**函数用于检测缺失数据

> **如何处理缺失数据？？？**

In [24]:
# 使用缺失（missing）或NA表示缺失数据。pandas的isnull和notnull函数可用于检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

- **Series**最重要的一个功能是，它会**根据运算的索引标签自动对齐数据**

- 结合**数据库操作**
    - 回顾常见SQL语句：增删改查、左右连接等操作

In [27]:
obj3 # 数据自动对齐

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

- **Series对象**本身及其**索引**都有一个**name属性**，该属性跟pandas其他的关键功能关系非常密切！！！

In [30]:
obj4.name = 'population'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

- **Series的索引**可以通过**赋值**的方式就地修改

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### **DataFrame**：数据框格式

> **DataFrame**是一个**表格型**的数据结构!

> **DataFrame**含有一组**有序的列**，每列可以是**不同的值类型**（数值、字符串、布尔值等）!!

> **DataFrame**既有**行索引**也有**列索引**，它可以被看做**由Series组成的字典**（共用同一个索引）!!!

> **DataFrame**中的数据是以一个或多个**二维块**存放的（而不是列表、字典或别的一维数据结构）!!!!

- **DataFrame**可以直接传入一个**由等长列表或NumPy数组**组成的**字典**

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],\
        'year': [2000, 2001, 2002, 2001, 2002, 2003],\
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [35]:
frame = pd.DataFrame(data)
frame # DataFrame会自动加上索引 与 Series类似 且 且全部列会被有序排列

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [36]:
frame.head() # head方法会选取前五行

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

- 如果指定了列序列，则DataFrame的列就会按照**指定顺序进行排列**

In [37]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

- 如果传入的列在数据中找不到，就会在结果中产生**缺失值**

In [38]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],\
                      index=['one', 'two', 'three', 'four','five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

- 通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

- **Note!**
    - 返回的Series拥有原DataFrame相同的索引，且其name属性也已经被相应设置

- **行**也可以通过位置或名称的方式进行获取，比如用**loc属性**

In [42]:
frame2.loc['three']  # loc 用法

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

- 列可以通过赋值的方式进行修改 

- 对空的属性赋予一个标量值或一组值

In [43]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

- 将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配

- 如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值

In [45]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [46]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

- 为不存在的列赋值会创建出一个新列。关键字**del**用于删除列

- 不能用**frame2.eastern**创建新的列

In [47]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [48]:
del frame2['eastern']  # del 关键字
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

# Note：

## 通过索引方式返回的列只是相应数据的视图而已，并不是副本！！！

## 对返回的Series所做的任何就地修改全都会反映到源DataFrame上！！！

## 通过Series的copy方法即可指定复制列！！！

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

### 嵌套字典

> 如果嵌套字典传给DataFrame，pandas就会被解释为：外层字典的键作为列，内层键则作为行索引

In [50]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},\
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [51]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [52]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [54]:
frame3.T # 转置操作 也可以明确指定索引

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [55]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [56]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

<!--DATAFRAME-->
<img align="center" style="padding-right:10px;" src="DataFrame.png">

In [59]:
frame3['Ohio'][:2]  # [:2]  等价于 [:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

- DataFrame的index和columns的name属性

In [61]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

- 跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据

In [62]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

- 如果DataFrame各列的数据类型不同，则值数组的dtype就会选用能兼容所有列的数据类型

In [63]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 索引对象

> pandas的索引对象负责管理轴标签和其他元数据

> 构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index

In [64]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [65]:
index = obj.index
print(index)
index[1:]

Index(['a', 'b', 'c'], dtype='object')


Index(['b', 'c'], dtype='object')

In [66]:
index[:-1]

Index(['a', 'b'], dtype='object')

- Index对象是不可变的，因此用户不能对其进行修改

- index[1] = 'd' # 类型错误

- 不可变可以使Index对象在多个数据结构之间安全共享

In [67]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [68]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [69]:
obj2.index is labels

True

In [70]:
print(frame3)
frame3.columns

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6


Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [71]:
'Ohio' in frame3.columns

True

In [72]:
2003 in frame3.index

False

- 与python的集合不同，pandas的Index可以包含重复的标签

In [73]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

<!--INDEX_D-->
<img align="center" style="padding-right:10px;" src="INDEX_D.png">

### 1.2 基本功能

> **重新索引reindex**

        其作用是创建一个新对象，它的数据符合新的索引 

In [74]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

- 用该Series的reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值

In [75]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

- 使用ffill可以实现前向值填充

In [76]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
obj3.reindex(range(6), method='ffill')  # ffill 方法

0      blue
2    purple
4    yellow
dtype: object


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

- 借助DataFrame，reindex可以修改（行）索引和列。只传递一个序列时，会重新索引结果的行

In [77]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),\
                     index=['a', 'c', 'd'],\
                     columns=['Ohio', 'Texas', 'California'])
print(frame)
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [78]:
states = ['Texas', 'Utah', 'California'] # 列可以用columns关键字重新索引
frame.reindex(columns=states) # reindex 重新索引

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

<!--REINDEX-->
<img align="center" style="padding-right:10px;" src="REINDEX.png">

In [79]:
frame.loc[['a', 'b', 'c', 'd'], states] # loc定位功能

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

> **剔除指定轴上的项**

        由于需要执行一些数据整理和集合逻辑，所以drop方法返回的是一个在指定轴上删除了指定值的新对象

In [81]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)
new_obj = obj.drop('c')
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


In [82]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

- 对于DataFrame，可以删除任意轴上的索引值

In [83]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),\
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],\
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- 用标签序列调用drop会从行标签（axis 0）删除值

In [84]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

- 通过传递axis=1或axis='columns'可以删除列的值

In [85]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [86]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

- **drop**会修改Series或DataFrame的大小或形状，可以就地修改对象，不会返回新的对象

In [87]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

> **索引**、**选择**与**过滤**

        Series索引的工作方式类似于NumPy数组的索引，只不过Series的索引值不只是整数

In [88]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print(obj)
print(obj['b'])
print(obj[1])
print(obj[2:4])
print(obj[['b', 'a', 'd']])
print(obj[[1, 3]])
obj[obj < 2]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64


a    0.0
b    1.0
dtype: float64

- 利用标签的切片运算与普通的Python切片运算不同，其末端是包含的

In [89]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

- 用切片可以对Series的相应部分进行设置

In [90]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

- 用一个值或序列对DataFrame进行索引其实就是获取一个或多个列

In [91]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),\
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],\
                    columns=['one', 'two', 'three', 'four'])
print(data)
print(data['two'])
data[['three', 'one']]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32


three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [92]:
print(data[:2])
data[data['three'] > 5]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [94]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

> **用loc和iloc进行选取** 针对于 **对于DataFrame的行的标签索引**

        使用轴标签（loc）或整数索引（iloc），从DataFrame选择行和列的子集

In [95]:
data.loc['Colorado', ['two', 'three']] # 通过标签选择一行和多列

two      5
three    6
Name: Colorado, dtype: int32

In [96]:
data.iloc[2, [3, 0, 1]] # 用iloc和整数进行选取

four    11
one      8
two      9
Name: Utah, dtype: int32

In [97]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [98]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [99]:
data.loc[:'Utah', 'two'] # 适用于一个标签或多个标签的切片的情况

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [100]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

<!--DATAFrame1-->
<img align="center" style="padding-right:10px;" src="DATAFrame.png">

> **整数索引 存在难点**

In [101]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [102]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

- 如果轴索引含有整数，数据选取总会使用标签

In [103]:
print(ser[:1])
print(ser.loc[:1])
ser.iloc[:1]

0    0.0
dtype: float64
0    0.0
1    1.0
dtype: float64


0    0.0
dtype: float64

> **算术运算和数据对齐**

        pandas可以对不同索引的对象进行算术运算
        
        在将对象相加时，如果存在不同的索引对，则结果的索引就是该索引对的并集。
        
        对于有数据库经验的用户，这就像在索引标签上进行自动外连接。

In [104]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],\
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [105]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

- 自动的数据对齐操作在不重叠的索引处引入了NA值。缺失值会在算术运算过程中传播

In [106]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),\ # 对于DataFrame，对齐操作会同时发生在行和列上
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),\
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
df2

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [107]:
df1 + df2 # 相加后将会返回一个新的DataFrame，其索引和列为原来那两个DataFrame的并集

# 因为'c'和'e'列均不在两个DataFrame对象中，在结果中以缺省值呈现。行也是同样

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

- 如果DataFrame对象相加，没有共用的列或行标签，结果都会是空

In [108]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)
df1 - df2

   A
0  1
1  2
   B
0  3
1  4


A   B
0 NaN NaN
1 NaN NaN

> **算术方法填充值** 

        用于当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值

In [109]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),\
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),\
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
print(df1)
df2

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [110]:
df1 + df2 # 相加时，没有重叠的位置就会产生NA值

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [111]:
df1.add(df2, fill_value=0) # 使用df1的add方法，传入df2以及一个fill_value参数

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [112]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [113]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

<!--Series_DataFrame-->
<img align="center" style="padding-right:10px;" src="Series_DataFrame.png">

In [114]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

> **DataFrame** 与 **Series**的运算

In [115]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0])
arr - arr[0]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]


array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

### 广播（broadcasting）

> 当我们从arr减去arr[0]，每一行都会执行这个操作。这就叫做广播（broadcasting）

In [5]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [6]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),\
                     columns=list('bde'),\
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame)
series

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

- 默认情况下，DataFrame和Series之间的算术运算会将Series的索引匹配到DataFrame的列，然后沿着行一直向下广播

In [7]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

- 如果某个索引值在DataFrame的列或Series的索引中找不到，则参与运算的两个对象就会被重新索引以形成并集

In [8]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [9]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

- 如果你希望匹配行且在列上广播，则必须使用算术运算方法

In [10]:
series3 = frame['d']
print(frame)
print(series3)
frame.sub(series3, axis='index')

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

> **函数应用** 与 **映射**

- NumPy的ufuncs（元素级数组方法）也可用于操作pandas对象

In [11]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
np.abs(frame)

               b         d         e
Utah   -0.562193 -0.176165 -1.556942
Ohio   -1.688722 -0.526995  1.244010
Texas   0.621097  0.614127  1.127279
Oregon  0.239753  0.624341  0.228371


b         d         e
Utah    0.562193  0.176165  1.556942
Ohio    1.688722  0.526995  1.244010
Texas   0.621097  0.614127  1.127279
Oregon  0.239753  0.624341  0.228371

In [12]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.309819
d    1.151335
e    2.800952
dtype: float64

- 这里的函数f，计算了一个Series的最大值和最小值的差，在frame的每列都执行了一次。结果是一个Series，使用frame的列作为索引

In [13]:
frame.apply(f, axis='columns')

Utah      1.380777
Ohio      2.932732
Texas     0.513151
Oregon    0.395969
dtype: float64

- 传递到apply的函数不是必须返回一个标量，还可以返回由多个值组成的Series

In [14]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.688722 -0.526995 -1.556942
max  0.621097  0.624341  1.244010

- 元素级的Python函数也是可以用的。假如你想得到frame中各个浮点值的格式化字符串，使用applymap即可

In [15]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.56  -0.18  -1.56
Ohio    -1.69  -0.53   1.24
Texas    0.62   0.61   1.13
Oregon   0.24   0.62   0.23

- 之所以叫做applymap，是因为Series有一个用于应用元素级函数的map方法

In [16]:
frame['e'].map(format)

Utah      -1.56
Ohio       1.24
Texas      1.13
Oregon     0.23
Name: e, dtype: object

> **排序** 与 **排名**

        根据条件对数据集排序（sorting）也是一种重要的内置运算。要对行或列索引进行排序（按字典顺序），
        可使用sort_index方法，它将返回一个已排序的新对象

In [17]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print(obj)
obj.sort_index()

d    0
a    1
b    2
c    3
dtype: int64


a    1
b    2
c    3
d    0
dtype: int64

- 对于DataFrame，则可以根据任意一个轴上的索引进行排序

In [18]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),\
                     index=['three', 'one'],\
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [19]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

- 数据默认是按升序排序的，但也可以降序排序

In [20]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

- 若要按值对Series进行排序，可使用其sort_values方法

In [21]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [22]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

- 在排序时，任何缺失值默认都会被放到Series的末尾

- 当排序一个DataFrame时，你可能希望根据一个或多个列中的值进行排序。将一个或多个列的名字传递给sort_values的by选项即可达到该目的

In [23]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(frame)
frame.sort_values(by='b')

   a  b
0  0  4
1  1  7
2  0 -3
3  1  2


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [24]:
frame.sort_values(by=['a', 'b']) # 要根据多个列进行排序，传入名称的列表即可

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

- 排名会从1开始一直到数组中有效数据的数量。接下来介绍Series和DataFrame的rank方法。

- 默认情况下，rank是通过“为各组分配一个平均排名”的方式破坏平级关系的

In [25]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [26]:
obj.rank(method='first') # 根据值在原数据中出现的顺序给出排名

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

- 条目0和2没有使用平均排名6.5，它们被设成了6和7，因为数据中标签0位于标签2的前面

In [27]:
# 可以按降序进行排名
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [28]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
print(frame)
frame.rank(axis='columns')

   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5


a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

<!--DF-->
<img align="center" style="padding-right:10px;" src="DF.png">

> **带重复标签的轴索引**

In [29]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [30]:
obj.index.is_unique # 索引的is_unique属性可以判定其值是否是唯一的

False

- 对于带有重复值的索引，数据选取的行为将会有些不同。如果某个索引对应多个值，则返回一个Series；而对应单个值的，则返回一个标量值

In [31]:
obj['a']

a    0
a    1
dtype: int64

In [32]:
obj['c']

4

In [33]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
print(df)
df.loc['b']

          0         1         2
a -1.025704  0.704453  0.433167
a -0.529218  0.282311  0.758666
b -1.079854  0.796732 -0.006064
b  1.500510 -0.307401 -1.642382


0         1         2
b -1.079854  0.796732 -0.006064
b  1.500510 -0.307401 -1.642382

> **汇总** 和 **描述性统计**

In [38]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],\
                   [np.nan, np.nan], [0.75, -1.3]],\
                  index=['a', 'b', 'c', 'd'],\
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [39]:
df.sum() # 调用DataFrame的sum方法将会返回一个含有列的和的Series

one    9.25
two   -5.80
dtype: float64

In [36]:
df.sum(axis=1) # 与下面等价

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [40]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [41]:
df.mean(axis='columns', skipna=False) # NA值会自动被排除，除非整个切片（这里指的是行或列）都是NA。通过skipna选项可以禁用该功能

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [42]:
df.idxmax() # 返回的是间接统计

one    b
two    d
dtype: object

In [43]:
df.cumsum() # 累计

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [44]:
df.describe()# describe用于一次性产生多个汇总统计

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [45]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4) # 对于非数值型数据，describe会产生另外一种汇总统计

In [46]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

> **相关系数** 和 **协方差**

> **唯一值**、**值计数** 和 **成员**

In [49]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [50]:
uniques = obj.unique() # unique可以得到Series中的唯一值数组
uniques # 返回的唯一值是未排序的

array(['c', 'a', 'd', 'b'], dtype=object)

In [51]:
obj.value_counts() # value_counts用于计算一个Series中各值出现的频率 

a    3
c    3
b    2
d    1
dtype: int64

In [52]:
pd.value_counts(obj.values, sort=False) # 也可用于任何数组或序列

c    3
b    2
d    1
a    3
dtype: int64

In [53]:
print(obj)
mask = obj.isin(['b', 'c']) # isin用于判断矢量化集合的成员资格，可用于过滤Series中或DataFrame列中数据的子集
print(mask)
obj[mask]

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object
0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool


0    c
5    b
6    b
7    c
8    c
dtype: object

In [54]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match) # Index.get_indexer可以给你一个索引数组，从可能包含重复值的数组到另一个不同值的数组

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [55]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

- 将pandas.value_counts传给该DataFrame的apply函数

In [56]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

### Discussion

> **Feedback**

### Conclusion

> **Summary**